BookManager/Controllers/AuthorsController.cs
using System.Linq;
using System.Web.Mvc;

using BookManager.DataAccess;

namespace BookManager.Controllers
{
    public class AuthorsController : BaseController
    {
        /// <summary>
        /// Create an author
        /// </summary>
        [HttpGet]
        public ActionResult Create()
        {
            var author = new Author();

            return View(author);
        }

        /// <summary>
        /// Save the Created Author to the database
        /// </summary>
        /// <param name="author"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }

            bookDB.Authors.Add(author);

            bookDB.SaveChanges();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// View Details of an Author
        /// </summary>
        /// <param name="authorID"></param>
        [HttpGet]
        public ActionResult Details(int authorID)
        {
            var author = bookDB.Authors.Find(authorID);

            return View(author);
        }

        /// <summary>
        /// Edit an Author
        /// </summary>
        /// <param name="authorID"></param>
        [HttpGet]
        public ActionResult Edit(int authorID)
        {
            var author = bookDB.Authors.Find(authorID);

            return View(author);
        }

        /// <summary>
        /// Save the Edits of the Author to the database
        /// </summary>
        /// <param name="author"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }

            bookDB.Entry(author).State = System.Data.Entity.EntityState.Modified;
            bookDB.SaveChanges();

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Delete an Author
        /// </summary>
        /// <param name="authorID"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public void Delete(int authorID)
        {
            var author = bookDB.Authors.Find(authorID);

            bookDB.Authors.Remove(author);

            bookDB.SaveChanges();
        }

    }
}

BookManager/Controllers/BooksController.cs
using System.Data.Entity;
using System.Web.Mvc;

using BookManager.DataAccess;
using BookManager.ViewModels;

namespace BookManager.Controllers
{
    public class BooksController : BaseController
    {
        /// <summary>
        /// Create a book
        /// </summary>
        [HttpGet]
        public ActionResult Create()
        {
            return View(new BookViewModel());
        }

        /// <summary>
        /// Save the created book to the database
        /// </summary>
        /// <param name="bookVM"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookViewModel bookVM)
        {
            if (!ModelState.IsValid)
            {
                return View(bookVM);
            }

            bookDB.Books.Add(bookVM.Book);

            bookDB.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Show a Book's details
        /// </summary>
        /// <param name="bookID"></param>
        [HttpGet]
        public ActionResult Details(int bookID)
        {
            var book = bookDB.Books.Find(bookID);

            return View(book);
        }


        /// <summary>
        /// Edit a Book details
        /// </summary>
        /// <param name="bookID"></param>
        [HttpGet]
        public ActionResult Edit(int bookID)
        {
            var book = bookDB.Books.Find(bookID);

            return View(book);
        }

        /// <summary>
        /// Save the edits to the book to the database
        /// </summary>
        /// <param name="book"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            if (!ModelState.IsValid)
            {
                return View(book);
            }

            bookDB.Entry(book).State = EntityState.Modified;
            bookDB.SaveChanges();

            return RedirectToAction("Details", new { bookID = book.BookID });
        }

        /// <summary>
        /// Delete a book
        /// </summary>
        /// <param name="bookID"></param>

        [HttpGet]
        public ActionResult Delete(int bookID)
        {
            return View(bookDB.Books.Find(bookID));
        }

        /// <summary>
        /// Delete a book from the database
        /// </summary>
        /// <param name="bookID"></param>
        [ActionName("Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int bookID)
        {
            var bookToDelete = bookDB.Books.Find(bookID);

            bookDB.Books.Remove(bookToDelete);

            bookDB.SaveChanges();

            return RedirectToAction("Index", "Home");
        }


    }
}

BookManager/Views/Authors/Create.cshtml
@model BookManager.DataAccess.Author

@{
    ViewBag.Title = "Create an Author";
}

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(m => m.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.FullName, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.FullName, "Full name is required", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(m => m.BiographyNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(m => m.BiographyNotes, 5, 80, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.BiographyNotes, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                    <div class="col-md-6">
                        <a href="@Url.Action("Index", "Home")" class="btn btn-danger">Cancel</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

BookManager/Views/Authors/Delete.cshtml
@model BookManager.DataAccess.Author

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-md-12">
        <h2>Are you sure you want to delete this Author?</h2>
        <h3>Author: @Model.FullName with @Model.Books.Count book(s)</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("DeleteBook", "Authors", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => m.AuthorID)

            <div class="row">
                <div class="col-md-6">
                    <input type="submit" value="Delete" class="btn btn-default col-md-6" />
                </div>
                <div class="col-md-6">
                    <a href="@Url.Action("Details", "Authors", new { authorID = Model.AuthorID })" class="btn btn-danger col-md-6">Cancel</a>
                </div>
            </div>

        }
    </div>
</div>

BookManager/Views/Authors/Details.cshtml

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>


BookManager/Views/Authors/Edit.cshtml
@model BookManager.DataAccess.Author

@{
    ViewBag.Tile = "Edit Author";
}

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(m => m.AuthorID)


            <div class="form-group">
                @Html.LabelFor(m => m.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-4">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
                <div class="col-md-6">
                    <a href="@Url.Action("Details", "Books", new { bookID = Model.BookID })" class="btn btn-danger">Cancel</a>
                </div>
            </div>
        </div>
        }
    </div>
</div>