BookManager/ViewModels/BookViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

using BookManager.DataAccess;

namespace BookManager.ViewModels
{
    public class BookViewModel
    {
        public Book Book { get; set; }


        /// <summary>
        /// Get a list of Authors
        /// </summary>
        public IEnumerable<SelectListItem> Authors
        {
            get
            {
                return new SelectList(
                        new BookManagerEntities().Authors,
                        nameof(Author.AuthorID),
                        nameof(Author.FullName)
                    );
            }
        }

    }
}

BookManager/Controllers/BooksController.cs
using System.Data.Entity;
using System.Web.Mvc;

using BookManager.DataAccess;
using BookManager.ViewModels;

namespace BookManager.Controllers
{
    public class BooksController : BaseController
    {
        /// <summary>
        /// Create a book
        /// </summary>
        [HttpGet]
        public ActionResult Create()
        {
            return View(new BookViewModel());
        }

        /// <summary>
        /// Save the created book to the database
        /// </summary>
        /// <param name="bookVM"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookViewModel bookVM)
        {
            if (!ModelState.IsValid)
            {
                return View(bookVM);
            }

            bookDB.Books.Add(bookVM.Book);

            bookDB.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Show a Book's details
        /// </summary>
        /// <param name="bookID"></param>
        [HttpGet]
        public ActionResult Details(int bookID)
        {
            var book = bookDB.Books.Find(bookID);

            return View(book);
        }


        /// <summary>
        /// Edit a Book details
        /// </summary>
        /// <param name="bookID"></param>
        [HttpGet]
        public ActionResult Edit(int bookID)
        {
            var book = bookDB.Books.Find(bookID);

            return View(book);
        }

        /// <summary>
        /// Save the edits to the book to the database
        /// </summary>
        /// <param name="book"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            if (!ModelState.IsValid)
            {
                return View(book);
            }

            bookDB.Entry(book).State = EntityState.Modified;
            bookDB.SaveChanges();

            return RedirectToAction("Details", new { bookID = book.BookID });
        }

        /// <summary>
        /// Delete a book
        /// </summary>
        /// <param name="bookID"></param>

        [HttpGet]
        public ActionResult Delete(int bookID)
        {
            return View(bookDB.Books.Find(bookID));
        }

        /// <summary>
        /// Delete a book from the database
        /// </summary>
        /// <param name="bookID"></param>
        [ActionName("Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int bookID)
        {
            var bookToDelete = bookDB.Books.Find(bookID);

            bookDB.Books.Remove(bookToDelete);

            bookDB.SaveChanges();

            return RedirectToAction("Index", "Home");
        }


    }
}

BookManager/Controllers/NotesController.cs
using System.Web.Mvc;

using BookManager.DataAccess;

namespace BookManager.Controllers
{
    public class NotesController : BaseController
    {
        /// <summary>
        /// Create a note for a book
        /// </summary>
        /// <param name="bookID"></param>

        [HttpGet]
        public ViewResult Create(int bookID)
        {
            var note = new Note();

            note.Book = bookDB.Books.Find(bookID);

            return View(note);
        }

        /// <summary>
        /// Save the new note to the database
        /// </summary>
        /// <param name="note"></param>

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Note note)
        {
            bookDB.Notes.Add(note);

            bookDB.SaveChanges();

            return RedirectToAction("Details", "Books", new { bookID = note.BookID });
        }


        /// <summary>
        /// Delete a Note from the database
        /// </summary>
        /// <param name="noteID"></param>
        [HttpPost]
        public ActionResult Delete(int noteID)
        {
            var note = bookDB.Notes.Find(noteID);

            bookDB.Notes.Remove(note);

            bookDB.SaveChanges();

            return RedirectToAction("Details", "Books", new { bookID = note.BookID });
        }


    }
}

BookManager/Controllers/TagsController.cs
using System.Linq;
using System.Web.Mvc;

using BookManager.DataAccess;
using BookManager.ViewModels;

namespace BookManager.Controllers
{
    public class TagsController : BaseController
    {
        /// <summary>
        /// Create a tag
        /// </summary>
        [HttpGet]
        public ActionResult Create()
        {
            return View(new Tag());
        }

        /// <summary>
        /// Save the created tag to the database
        /// </summary>
        /// <param name="tag"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tag tag)
        {
            bookDB.Tags.Add(tag);

            bookDB.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Add a Tag to a book
        /// </summary>
        /// <param name="bookID"></param>
        [HttpGet]
        public ActionResult AddTagToBook(int bookID)
        {
            var tbvm = new TagBookViewModel();

            tbvm.BookID = bookID;

            return View(tbvm);
        }

        /// <summary>
        /// Save the added tag to a book to the database
        /// </summary>
        /// <param name="tbvm"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddTagToBook(TagBookViewModel tbvm)
        {
            var btt = bookDB.BookToTags.Create();

            btt.BookID = tbvm.BookID;
            btt.TagID = tbvm.TagID;

            bookDB.BookToTags.Add(btt);
            bookDB.SaveChanges();

            return RedirectToAction("Details", "Books", new { bookID = tbvm.BookID });
        }



        /// <summary>
        ///just a simple HttpGet method to remove a tag from a book.
        ///in a production/real app example, this would be an HttpPost so that someone couldnt just spam
        ///a bunch of requests to remove all tags from books.
        /// </summary>
        /// <param name="bookID"></param>
        /// <param name="tagID"></param>
        [HttpGet]
        public ActionResult RemoveTag(int bookID, int tagID)
        {
            var bookToTag = bookDB.BookToTags.FirstOrDefault(btt => btt.BookID == bookID && btt.TagID == tagID);

            bookDB.BookToTags.Remove(bookToTag);

            bookDB.SaveChanges();

            return RedirectToAction("Details", "Books", new { bookID = bookID });
        }

    }
}

BookManager/Views/Books/Create.cshtml
@model BookManager.ViewModels.BookViewModel

@{
    ViewBag.Title = "Add a New Book";
}

<div class="row">
    <div class="col-md-12">
        <h1>@ViewBag.Title</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(m => m.Book.AuthorID, "AuthorID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.Book.AuthorID, Model.Authors, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Book.AuthorID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Book.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.Book.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Book.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Book.YearPublished, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.Book.YearPublished, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Book.YearPublished, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Book.DateStarted, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.Book.DateStarted, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Book.DateStarted, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Book.DateFinished, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.Book.DateFinished, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Book.DateFinished, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Book.Review, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.Book.Review, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Book.Review, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Book.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.Book.Rating, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Book.Rating, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                    <div class="col-md-6">
                        <a href="@Url.Action("Index", "Home")" class="btn btn-danger">Cancel</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

BookManager/Views/Books/Delete.cshtml
@model BookManager.DataAccess.Book

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-md-12">
        <h2>Are you sure you want to delete this book?</h2>
        <h3>Book: @Model.Title by @Model.Author.FullName</h3>
        <h3>Note Count: @Model.Notes.Count</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => m.BookID)

            <div class="row">
                <div class="col-md-12">
                    <p class="text-warning"><strong>WARNING! All book detail information and all @Model.Notes.Count note(s) associated with the book will be deleted permanently!</strong></p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <input type="submit" value="Delete" class="btn btn-danger col-md-6" />
                </div>
                <div class="col-md-6">
                    <a href="@Url.Action("Details", "Book", new { bookID = Model.BookID })" class="btn btn-default col-md-6">Cancel</a>
                </div>
            </div>
        }
    </div>
</div>

BookManager/Views/Books/Details.cshtml
@model BookManager.DataAccess.Book

@{
    ViewBag.Title = "Book Details - " + Model.Title;
}

<div class="row">
    <div class="col-md-3">
        <a href="@Url.Action("Create", "Notes", new { bookID = Model.BookID })" class="btn btn-success col-md-12">
            <i class="glyphicon glyphicon-list-alt"></i>
            Add a Note
        </a>
    </div>
    <div class="col-md-3">
        <a href="@Url.Action("AddTagToBook", "Tags", new { bookID = Model.BookID })" class="btn btn-success col-md-12">
            <i class="glyphicon glyphicon-tag"></i>
            Add a Tag
        </a>
    </div>
    <div class="col-md-3">
        <a href="@Url.Action("Edit", new { bookID = Model.BookID })" class="btn btn-warning col-md-12">
            <i class="glyphicon glyphicon-pencil"></i>
            Edit
        </a>
    </div>
    <div class="col-md-3">
        <a href="@Url.Action("Delete", new { bookID = Model.BookID })" class="btn btn-danger col-md-12">
            <i class="glyphicon glyphicon-trash"></i>
            Delete
        </a>
    </div>
</div>


<div class="row">
    <div class="col-md-4">
        <h4>Details</h4>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(m => m.Title)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(m => m.Author.FullName)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Author.FullName)
            </dd>
            <dt>
                @Html.DisplayNameFor(m => m.YearPublished)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.YearPublished)
            </dd>
            <dt>
                @Html.DisplayNameFor(m => m.DateStarted)
            </dt>
            <dd>
                @(Model.DateStarted?.ToShortDateString())
            </dd>
            <dt>
                @Html.DisplayNameFor(m => m.DateFinished)
            </dt>
            <dd>
                @(Model.DateFinished?.ToShortDateString())
            </dd>
            <dt>
                @Html.DisplayNameFor(m => m.Rating)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Rating)
            </dd>


        </dl>
    </div>
    <div class="col-md-4">
        <h4>Tags</h4>
        @if (Model.BookToTags.Any())
        {
            <table class="table table-striped table-hover">
                @foreach (var btt in Model.BookToTags)
                {
                    <tr>
                        <td>@btt.Tag.TagContent</td>
                        <td>
                            <a href="@Url.Action("RemoveTag", "Tags", new { bookID = Model.BookID, tagID = btt.TagID })" class="alert-danger" title="Click to remove this tag from this book">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No tags added yet.</p>
        }
    </div>
    <div class="col-md-4">
        <h4>@Html.DisplayNameFor(m => m.Review)</h4>

        <p>@Html.DisplayFor(m => m.Review)</p>
    </div>
</div>


<div class="row">
    <div class="col-md-12">

        <h4>Notes</h4>

        @if (Model.Notes.Any())
        {
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Page Number</th>
                        <th>Note Content</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var note in Model.Notes.OrderBy(n => n.PageNumber))
                    {
                        <tr>
                            <td>@note.PageNumber</td>
                            <td>@note.NoteContent</td>
                            <td>
                                <a href="@Url.Action("Edit", "Notes", new { noteID = note.NoteID })" class="btn btn-warning">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                    Edit
                                </a>
                            </td>
                            <td>
                                <a href="#" onclick="deleteNote(@note.NoteID)" class="btn btn-danger">
                                    <i class="glyphicon glyphicon-trash"></i>
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No notes have been added to this book.</p>
        }

    </div>
</div>

<script type="text/javascript">
    function deleteNote(noteID) {
        $.post('@Url.Action("Delete", "Notes")', noteID)
            .done(function () {
                location.reload();
            })
            .fail(function () {
                window.alert("Failed to delete this Note. NoteID: " + noteID + ".");
            });
    }
</script>

BookManager/Views/Books/Edit.cshtml
@model BookManager.DataAccess.Book

@{
    ViewBag.Title = "Edit Book: " + Model.Title + " by " + Model.Author.FullName;
}

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(m => m.BookID)
                @Html.HiddenFor(m => m.AuthorID)

                <div class="form-group">
                    @Html.LabelFor(m => m.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.YearPublished, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.YearPublished, new { htmlAttributes = new { @class = "form-control", style = "max-width:80px;", maxlength = "4" } })
                        @Html.ValidationMessageFor(m => m.YearPublished, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.DateStarted, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.DateStarted, new { htmlAttributes = new { @class = "form-control", style = "max-width: 200px", @type = "date" } })
                        @Html.ValidationMessageFor(m => m.DateStarted, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.DateFinished, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.DateFinished, new { htmlAttributes = new { @class = "form-control", style = "max-width: 200px", @type = "date" } })
                        @Html.ValidationMessageFor(m => m.DateFinished, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Review, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(m => m.Review, 20, 100, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Review, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.Rating, new { htmlAttributes = new { @class = "form-control", style = "max-width: 80px" } })
                        @Html.ValidationMessageFor(m => m.Rating, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-4">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                    <div class="col-md-6">
                        <a href="@Url.Action("Details", "Books", new { bookID = Model.BookID })" class="btn btn-danger">Cancel</a>
                    </div>
                </div>
            </div>
        }

    </div>
</div>
